django/asgiref

asgiref/conformance.py, asgiref/inmemory.py
The following code acts different with the inmemory layer and the redis layer
```python
message = {'foo': [1,2,3]}
Channel('some_channel').send(message)
message['foo'][0] = 'new value'
```
The inmemory layer sends the object ```message ``` to the receiver and therefore the inner list as reverence. The redis layer creates a string from the message at the moment ```Channel(...).send()``` is called and therefore a copy of the message.
This pull request fixes this and both layers should work the same.
=> Altert Channel.send on the inmemory layer to send a copy of the message.

asgiref/base_layer.py
This method used in all already implemented backends. Also it's required in the conformance test. I think it worth to add it in the base class.
=> Add missed abstract method.

asgiref/inmemory.py
Removing redefinitions of `ChannelFull` and `MessageTooLarge`, as they are already defined in the`BaseChannelLayer`
=> Removing exceptions' redefinitions

.gitignore, .travis.yml, README.rst, asgiref/conformance.py, setup.py, tox.ini
This pull requests introduced tox to be able to test against multiple Python versions locally, and configures tox and Travis so that they test against all Python versions supported by Channels. I also added a bit of documentation and cleanup.
I intend to make similar changes to the other Channels projects, so this pull request is a good occasion to discuss whether the same changes can and should be made to the other projects.
=> tox, and all the Pythons 

asgiref/base_layer.py
Since `valid_channel_names` is only a utility function wrapping `valid_channel_name`, it should accept the same parameters.
=> Valid channel names

asgiref/conformance.py
Added an option to `ConformanceTestCase` that allows the test case to retry receiving. This is necessary for testing `ChannelLayer` implementations that do not guarantee a response will be returned on every `receive()` call, even when there are messages on the channel. This would be the case, for example, for a channel layer designed for a multi-worker environment with multiple backing hosts, that checks a different host on each call.
Also fixed `test_send_recv` so that it does not depend on the order in which messages are returned, since order is not guaranteed in the spec.
=> Optionally retry on receive in ConformanceTest

asgiref/conformance.py, asgiref/inmemory.py
Just to be more precise.
Should we do the same for `twisted` extension?
=> Verify async extension against its methods.

asgiref/base_layer.py
Got hit by a situation where my group name was over 100 characters but the system was saying it contained illegal characters, which was a bit confusing. Trying to improve the messages coming out of the validation with these commits.
* Functions valid_channel_name and valid_group_name were using almost the same error message. Unified both to use the class 'invalid_name_error' attribute. This also added to the error message the underscore as a valid character. It was a valid character all the time but was missing from the raised error.
* Refactor BaseChannelLayer.match_type_and_length. Channel and group names are also restricted in length and type, but if those fail to validate we got a validation message related to characters in the name. Raise a separate TypeError to indicate clearly …
=> Improve channel and group name validation

asgiref/testing.py, tests/test_testing.py
Addresses #32.
On my computer it took < 0.001 s to send a message via (Channels') `group_send` using the `InMemoryChannelLayer`. Therefore an attempt after 0.01 s should actually be enough. Please let me know if you prefered a simpler implementation.
**ToDo**
=> ApplicationCommunicator's receive_nothing

docs/extensions.rst, docs/index.rst
This allows HTTP responses such as 401, authentication required to be
sent to the client by a framework that requires authenticated
websocket connections. It would also allow for redirect responses or
other more exotic framework responses.
This specifies how a client should indicate that a HTTP/2 server push
should be initiated.
=> WWW Spec changes

specs/asgi.rst
This makes it clear that the send awaitable callable should unblock
and act as a no-op after the connection has closed.
=> Clarify backpressure handling on connection close

specs/www.rst
This allows for ASGI applications to call the receive after sending a
response by indicating the application should receive a disconnect
message. This in turn allows the sending and receiving tasks to have
separate lifespans.
The use case I have in mind (and use in Quart) is something like,
```
async def application_instance(receive, send):
while True:
message = await receive()
task = asyncio.ensure_future(sending_task(send))  # Separate lifespan
if message['type'] == 'http.disconnect':
task.cancel()
break
...
```
At the moment Uvicorn (as the motivating example) interprets this a different want and raises an error in the receive after the sending is complete.
=> Allow for http.disconnect after response sending

specs/asgi.rst
This allows frameworks to know what version of the ASGI specification
the server implements. This in turn allows features to be added to the
specification for framework usage.
=> Add ASGI versioning to the scope definition

docs/implementations.rst
Drop API Star, since from 0.6 onwards it's [descoped into a framework-agnostic suite of API tools](https://github.com/encode/apistar/pull/624), rather than a complete server implementation. (Starlette has picked up the mantle for my own work on an ASGI framework implementation.)
=> Drop API Star from implementations.

docs/specs/index.rst, specs/asgi.rst, specs/lifespan.rst
This allows for frameworks to provide the ability to call async code
to setup before a single request, e.g. creating a connection pool, and
cleanup after all requests, e.g. releasing the connection pool
connections.
=> Add a lifespan protocol

specs/lifespan.rst
I just found out that I've implemented the lifespan protocol the wrong way in [Asgish](https://github.com/almarklein/asgish), because I misread the docs. This change fixes some ambiguities with earlier naming.
=> Fix cleanup/shutdown

asgiref/sync.py
Refs #71
In versions of Python that support contextvars, threadpool operations should run in the same the context as the parent.
Prompted by https://github.com/getsentry/sentry-python/issues/162#issuecomment-443415106
Note that Python 3.8 might include [a `preserve_context` keyword argument](https://bugs.python.org/issue34014).
=> Threadpool operations should run in same contextvars context.

specs/www.rst
RFC 7320 section 5.3 allows for the request target to be in an
absolute form (5.3.1) which servers MUST allow. The current ASGI
servers (Hypercorn, Uvicorn & Daphne) will all pass on the full
request-target (minus query string) to the ASGI application rather
than, as the previous version of this specification suggested, just
the path part of the URL. This should help ASGI app developers
understand whether to assume the path will always be just the path.
=> Clarify www spec for path definition

specs/www.rst
This is required now that websockets over HTTP/2 has been defined in
RFC 8441.
=> Add http_version to the Websocket scope

specs/www.rst
This allows an application to specify additional headers to send to
the client in the handshake response, for example cookie settings.
(See https://gitlab.com/pgjones/quart/issues/206 for a motivating request).
=> Allow headers to be specified in the accept message

asgiref/compatibility.py, asgiref/testing.py, asgiref/wsgi.py, specs/asgi.rst, specs/lifespan.rst, specs/www.rst, tests/test_compatibility.py
This branch both adds the doc/spec change for single-callable-style applications, as well as upgrading the lifecycle protocol to have better failure modes.
=> 3.0: Single-callable style applications & lifecycle improvements

docs/extensions.rst, docs/implementations.rst, docs/introduction.rst, docs/specs/index.rst, specs/asgi.rst, specs/lifespan.rst, specs/www.rst
Hey folks, I'm keen on making myself useful toward getting ASGI into Django (I talked with @andrewgodwin at DjangoCon US 2018 about it and recently saw @tomchristie's DjangoCon EU 2019 keynote) and I'm starting pretty well from scratch by reading the ASGI specification docs. Since I've just gone through the thing, I wanted to contribute some clarifying changes to things that tripped me up that I hope will provide some value to others.
The biggest change was moving data types for protocol specifications to a consistent place for better readability, e.g.:
* `type`: `http`
* `asgi["version"]`: The version of the ASGI spec, as a string
* `type` (_Unicode string_) – `"http"`
* `asgi["version"]` (_Unicode string_) – Version of the ASGI spec
The rest being mostly minor stuff for consistency:
* …
=> Clarify general and spec documentation

README.rst, docs/conf.py
Resolves #84 
* Comment out `html_sidebars` lines from `docs/conf.py` to get default working Sphinx theme when building docs out of the box
* Add section in `README.rst` about how to build the docs (this can go somewhere else if it's starting to feel lengthy?)
=> Fix and document docs process

docs/introduction.rst
The Python code example function body was indented 8 spaces instead of 4.
=> Cleaner indentation of code example

.travis.yml
It is not very useful to get a failure because of style issues, without
any feedback on the actual tests.  Also black should display what it
would change (`--diff`).
=> ci: run linting after tests, output diff

setup.cfg
Nobody is using test selection?!
=> pytest: use testpaths instead of addopts

asgiref/sync.py
It is available since Python 3.5, and makes the check much simpler
(especially not having to catch RuntimeError for the common case).
=> AsyncToSync: use asyncio._get_running_loop for check

asgiref/sync.py, tests/test_sync.py
Closes #103. 
Test case reproducing issue locally. Passes on py36. Fails on py37. Seeing how it goes on Travis. 
Update: fix added.
=> Fixed unittest collection with @async_to_sync on Python 3.7.

asgiref/sync.py, tests/test_sync.py
This change is needed to fix a test failure (test_process_template_response_returns_none) in andrewgodwin/django on async_views branch.
=> Copy method's __self__ in sync_to_async

asgiref/wsgi.py
In order to properly support applications which are not mounted at the
root, we need to pass the ASGI `root_path` as the WSGI `SCRIPT_NAME`.
=> Made AsgiToWsgi pass root_path as SCRIPT_NAME

docs/extensions.rst, specs/www.rst
Specifically that Pseudo headers are not an application concern, but
rather are a concern of the server (as they are specific to the
protocol).
Additionally this requires an ASGI server to create a host
header. Doing so ensures that ASGI applications can continue to assume
a host header exists.
Note there can only be one host header which should be at the start as
per RFC-7230, https://tools.ietf.org/html/rfc7230#section-5.4.
=> Clarify Pseudo header treatment

MANIFEST.in
In OpenBSD we like to gave the regression tests for testing and making sure we haven't broken things when updating other ports. 
This will include those tests in the PyPI tarball for future releases.
=> Include regression tests in MANIFEST.in to include them in PyPI tarball

docs/introduction.rst
As per [spec](https://asgi.readthedocs.io/en/latest/specs/www.html#response-start), this should be a list of two-lists
=> Fix headers example in introduction

setup.py
This will prevent installation on unsupported Python versions.
=> Declare python_requires in setup.py

asgiref/sync.py
`asyncio.all_tasks()` first appeared in Python 3.7. I am not familiar with what syntax changes would be necessary to support Python 3.5.
=> Cancel and wait for tasks before asyncgen shutdown.

.gitignore, asgiref/sync.py, tests/test_sync_contextvars.py
This PR changes `SyncToAsync` to check if downstream code made changes to any contextvars, and propagates those changes back to the current context, so they'll be available for future downstream consumers.
I work on Elastic's APM team, and our [python agent](https://github.com/elastic/apm-agent-python) uses `contextvars` to keep track of the running transaction object during a request in Django. We create that transaction object [in our `request_started` signal handler](https://github.com/elastic/apm-agent-python/blob/11c64362fe5189ee30936eb8791b8e1368371dd0/elasticapm/contrib/django/apps.py#L147). The reason we do it there instead of in our middleware is so we can measure time spent in the resolver and any middleware that execute before ours.
However, for ASGI, that transaction is no …
=> [RFC] Propagate changes to contextvars "upstream" for SyncToAsync

asgiref/sync.py, tests/test_sync.py
This change is required to fix test failure reported in https://github.com/django/django/pull/11650.
=> Copied method's __self__ in async_to_sync.

asgiref/local.py, tests/test_local.py
This one stores on threads/tasks directly, much like the implementation in the standard library. This removes the need for garbage-collection of local storage, and should be more compatible with libraries that override `threading`, like `gevent`.
Fixes #144.
=> New implementation of local.Local

setup.cfg
The package is Python 3 only, as such the wheel should not be marked as
"universal" because it does not support Python 2.
https://wheel.readthedocs.io/en/stable/user_guide.html?highlight=universal#building-wheels
> If your project contains no C extensions and is expected to work on
> both Python 2 and 3, …
=> Remove bdist_wheel from setup.cfg

docs/introduction.rst
This PR is a minor wording update for consistency.
Making the types of the parameters passed to an application a bit more explicit and making more explicit that the functions are "asynchronous callables", to use the same wording used in other parts of the spec and in the Python docs.
It also updates one of the example event messages to show what could be received in a `receive` event message. Currently, the text refers to `receive` but the example is for `send`. As there are other examples for `send` I thought it would be better to have one example for `receive`.
---
This is part of several PRs I'm making while reading and re-reading the spec several times.
The main purpose is to try and update the parts that contained text based on the 2-callable version (`2.0`) and to clarify a bit more …
=> 📝 Minor wording update: Introduction

specs/lifespan.rst
This PR is a minor wording update for the Lifespan sub-spec.
It includes some minor rewordings for consistency with other parts of the spec.
And some minor updates to make the types and directions of events a bit more explicit and reduce any possible ambiguity.
---
This is part of several PRs I'm making while reading and re-reading the spec several times.
The main purpose is to try and update the parts that contained text based on the 2-callable version (2.0) and to clarify a bit more the parameters passed to an ASGI app and types and direction of events.
=> 📝 Minor wording update: Lifespan sub-spec

.travis.yml, setup.cfg
AFAICS there's no need to pin the test dependencies. 
Causing hard to track inconsistencies on downstream, e.g. django/daphne#322
Travis ships [with an old Pytest pre-installed](https://travis-ci.org/github/django/asgiref/jobs/696964456#L193-L194), so it's necessary to update it before we begin.
=> Unpinned test dependencies.

docs/implementations.rst
This adds FastAPI to the ASGI implementations :tada: :rocket:
=> 📝 Add FastAPI to Implementations

asgiref/sync.py, tests/test_sync_contextvars.py
sync_to_async already makes sure that contextvars are properly
propagated, but async_to_sync does not attempt to do this at all.
In Django 3.1, this fixes the behavior of got_request_exception which
would otherwise be called in a different context than before_request or
after_request under the following circumstances:
1. An ASGI request has been made
2. There is at least one sync middleware
Fix #170
=> Propagate and restore contextvars in async_to_sync

specs/www.rst
this happens twice in the docs (I didnt see more) and it happens when titles are the same, in that case sphinx generates an anchor link for the 2nd one that looks like this:
https://asgi.readthedocs.io/en/latest/specs/www.html#id1
https://asgi.readthedocs.io/en/latest/specs/www.html#id2
the 1st one is for the Connection scope, it's used twice for http and socket protocol, I dealt with it adding HTTP / Websocket
the 2nd one is for the receive disconnect message,  I dealt with it adding an explicit anchor reference on the 2nd one
=> Anchor links in docs are sometimes not "nice"

specs/lifespan.rst, specs/www.rst
This clarifies that optional implies the key is missing, not that the
key is present with a value of say None (as optional means in the
Python typing context).
=> Clarify Optional meaning

asgiref/wsgi.py, tests/test_wsgi.py
This fixes the bug mentioned in #195 where a WSGI server should not send more
output than Content-Length, if the header is present.
After reading more of the spec, this also adds the specified behavior of stopping
the response iteration as soon as we have enough bytes.
The WSGI spec also says that a response body that is too short should also log
or raise an error and close the connection.
This part seems hard to do correctly while also handling HEAD requests:
these requests can contain a Content-Length header and, depending on who you
ask, the WSGI application should or should not return the response body and
expect the WSGI server to remove it. I was not familiar with the issue but it seems
there's no clear consensus so I've opted to leave it alone :)
Since write() is not present in …
=> Fixes #195: Clamp WsgiToAsgi response body using Content-Length value

specs/www.rst
As the server could be serving over a Unix socket or the client could
connect over one the ``client`` and ``server`` ASGI scope values
should allow the path (address) alone with the port as ``None`` (as
the socket has no port).
=> Allow for unix sockets in the ASGI scope

specs/www.rst
This was missed in e14932bcc6c0287898ae2ba24d1f872a2c5aedc5 but
applies.
=> Copy unix socket usage to Websocket scope

specs/www.rst
There was an invalid character in `missing` that showed up as `miss ing`.
=> Remove typo from invalid character.

README.rst, asgiref/sync.py, tests/test_sync.py
As discussed in #223 this PR implements context-specific thread pool capabilities. It does so by creating an input variable (definitely open to updating the name of that input parameter 😛 ) allowing callers of `sync_to_async` to specify a function that returns the current context.
The intended usage of this API is to use [`contextvars` in Django](https://github.com/django/django/compare/master...a-feld:asyncio-perf-improvements) to allow a thread pool per-request.
This PR maintains the existing safety of using a global thread pool per-process by default.
=> Add support for context-specific thread pool executors.

asgiref/typing.py, setup.cfg
These are useful for users of asgiref to type check their ASGI
usage. It also serves as the reference typing for the ASGI
Specification.
=> Add typing for ASGI Scopes, messages, and frameworks

MANIFEST.in
This allows the new type hints for the ASGI scopes and messages to be
used. Without this mypy ignores anything from asgiref.
=> Add a py.typed marker file for PEP 561 compliance

README.rst, asgiref/sync.py, tests/test_sync.py, tests/test_sync_contextvars.py
Rather than using an external context management function, this commit
updates the thread_sensitive mode to reference an internal contextvar.
This approach mainly allows for the thread executor to be shut down when
the context exits, rather than relying on the thread pool shutting down
when going out of scope.
This approach also has other advantages:
* Maintains the existing sync_to_async interfaces.
* Context variable management cannot be broken by omitting the
current_context_func arg
* This approach opens the door to more complex management techniques
such as enforcing a thread pool limit.
Django PR showing implementation: https://github.com/django/django/pull/13882
=> Internalize thread sensitive context management in asgiref/sync.py

asgiref/typing.py, specs/www.rst
This is allowed as per RFC 6455 but previously not supported in
ASGI. This allows servers/applications to use the reason if desired.
See also #234
=> Added reason to the WebSocket close

asgiref/sync.py, tests/test_sync.py
There are cases where it may be desirable to run certain sync_to_async callables in their own executor. For example, a user might want to allow a method to be run in small thread pool without affecting the loop's default thread pool. Or, a custom executor may be passed in to gather metrics about calls for certain decorated methods.
=> Parameterize executor

asgiref/sync.py, tests/test_sync.py
On Python < 3.8 a functool.partial is not detected as async function, which is due to a bug in inspect module, see: https://bugs.python.org/issue33261
This commit adds a proper type check for earlier Python versions and fixes #251
Idea taken from pgjones' [comment](https://github.com/django/asgiref/issues/251#issuecomment-814168943).
=> Fix type checks for functions passed to async_to_sync/sync_to_async

asgiref/compatibility.py, asgiref/server.py, asgiref/sync.py, tests/test_sync.py, tests/test_sync_contextvars.py, tox.ini
asyncio.get_event_loop was marked as deprecated, the documnetation
now refers to asyncio.get_running_loop([1])
asyncio.ensure_future issues a deprecation warning if there is no
running event loop([2]), so use asyncio.run which creates and destroys the
loop itself
asyncio.gather issues a warning if run outside of event
loop (i.e. there is no running event loop)([3]), so wrap it into an
async def
explicit passing of coroutine objects to asyncio.wait is deprecated
since 3.8([4]), so wrap them in asyncio.create_task
plus, add 3.10 to tox.ini
[1]: https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop
[2]: https://docs.python.org/3.10/library/asyncio-future.html#asyncio.ensure_future
[3]: https://docs.python.org/3.10/library/asyncio-task.html#asyncio.gather
[4]: …
=> Fix deprecation warnings for python 3.10

asgiref/sync.py
Use `@overload` to specify the two different sets of types for `sync_to_async()`. This prevents any errors in the example shown in #254.
=> Fix type hints for sync_to_async()

asgiref/sync.py, tests/test_sync.py
Raise an exception on potential deadlock where the single thread pool is awaited on while already being awaited on in the same context 
I'm using a context var here because I think setting an attribute would throw an exception outside of this scenario, if you had multiple 'main' threads just wanting to use the single thread executor, which would not deadlock
=> Raise on deadlock

asgiref/typing.py
@andrewgodwin We are annotating `uvicorn` with `asgiref` now, and possibly extending this idea to `Starlette`. So... Thanks for maintaining it! :)
While I was annotating `uvicorn`, I've noticed that `mypy` complains about the nonexistence of "extensions" so I added it. But after looking at the ASGI specs, it doesn't look like "extensions" is mandatory. Am I wrong?
As per #221 it was decided to use `Optional` to optional fields, instead of making the field optional _per se_, so I've created this PR.
=> 🐛 Fix extensions type on HTTPScope and WebsocketScope

asgiref/_pep562.py, asgiref/typing.py, setup.cfg, tests/test_deprecated_types.py, tox.ini
This is fundamentally unnecessary, so the rejecting this PR is understandable. But the correct name is WebSocket.
=> 📝 Rename Websocket by WebSocket

tests/test_sync.py
Something I noticed while working on #282, but which is not part of it.
=> fix `async_to_async` typo

tests/test_sync.py
These tests provide an example the issues I ran into while moving from asgiref 3.2.10 to 3.3+, which digging through issues here has suggested was not uncommon. Making `sync_to_async` default to `thread_sensitive=True` can cause deadlocks in previously functioning code. I've read and understood why the choice was made, and don't presently have any suggestions on how to better detect and avoid the situation, but figured the distilled scenario in test form might be useful regardless.
---
In these tests, we are waiting on a `mulitprocessing.Event` to be set, with the wait in `sync_to_async()`.
The event is being set in an `asyncio.Task` that sleeps and then calls set, also in `sync_to_async()`. This allows us to kick off the process that would `set()` the event in advance of `wait()`ing for …
=> New sync_to_async tests, one of which triggers a deadlock

asgiref/sync.py
Unless I'm missing runtime/implementation specific details, I can't see a reason the decision about whether to use `asyncio.current_task` or `asyncio.Task.current_task` cannot be decided once at import time.
My naive, underestimating guess is that when it was done in 51d5c4618a34a16cb6a14624e0e4d35dc92978ae and 768a0718269c309bf2a5a3c4c9558d55c56283d5 it was without the memory of there being an import-time branch covering the same Python versions in e3e1cc84612065b0b61c03e96fdfb8a7854a5f85.
This saves 1 `hasattr` call every time `mylocal.myvar` or `getattr(mylocal, 'myvar')` are used; timings are on a laptop so are y'know, fluxxy.
Before:
```
In [1]: from asgiref.local import Local
...: x = Local()
...: def timeonly():
...:     setattr(x, 'test', None)
...:     for _ in range(100_000): …
```
=> Hoist deciding which asyncio current_task to use to module definition time.

asgiref/local.py
It was last used prior to a0bbe901ffe19cd927219989b7125a920ea1e5c3 and tags < `3.2.6`
It may be going through an informal deprecation cycle, or it may've just been missed (wood for the trees etc). Either way, when it's appropriate, this should be OK to merge. One hopes.
=> Removed Local.CLEANUP_INTERVAL class variable which has been unused for a while

asgiref/compatibility.py, asgiref/sync.py, asgiref/timeout.py
Follows up on f53fbef (#289). Note that the module level variable used here differs, because it is already in use as the public function name.
As with that one, saves 1 `hasattr` call per usage, this time of of `asgiref.timeout.current_task`
=> timeout module: Hoist deciding which asyncio current_task to use to module definition time

.github/workflows/tests.yml, setup.cfg, tests/test_server.py
This also fixes deprecation warnings in `tests/test_server.py`:
```
tests/test_server.py::test_stateless_server
/asgiref/tests/test_server.py:108: DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()
tests/test_server.py::test_server_delete_instance
/asgiref/tests/test_server.py:135: DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()
```
=> Added testing for Python 3.10.

specs/www.rst
Those values were not up-to-date considering what is on the top of the page:
=> Fix allowed values for `spec_version` on WebSocket and HTTP Connection scopes

tests/test_sync.py
Option 2 to fix #313: make things pickle-friendly by rewriting the test to not use local functions.
=> rewrite the test to use no local functions

.pre-commit-config.yaml, setup.cfg, tests/test_server.py
This fixes running tests on Mac OS X, which lacks the `SOCK_NONBLOCK`
socket flag creation.
=> Remove `SOCK_NONBLOCK` from socket creation on tests

asgiref/sync.py, tests/test_sync.py
=> Preserve CurrentThreadExecutor across create_task

asgiref/sync.py, tests/test_sync.py
=> Don't warn 'non-async-marked callable' for async callable instance

asgiref/sync.py, tests/test_sync.py
i.e. passing an instance defining `async def __call__(...)` to `sync.SyncToAsync` will raise a `TypeError`
Refs: #324 
Fixes: #327
=> Disallow async callable class instances as callable for `sync.SyncToAsync`

.gitignore, asgiref/sync.py
Adds an `update_wrapper` in `SyncToAsync.__get__` to get more context out of the returned partial.
Same behavior as in `AsyncToSync`
=> Use update_wrapper in SyncToAsync.__get__

CHANGELOG.txt, asgiref/sync.py
This is a request-for-comment on the support for setting the `ASGI_THREADS` environment variable in `SyncToAsync`.
* For Daphne it doesn't work, since the we don't use the event loop returned by `get_event_loop()`. See https://github.com/django/daphne/issues/319
* `get_event_loop()` is deprecated, and will become an alias for `get_running_loop()` in a future Python version. This code will at that point raise a `RuntimeError` since there won't be a running event loop. 
* Even the _happy path_ assumes `asgiref.sync` is imported on the main thread, since it's only then that a new loop is automatically created. 
For the Daphne issue, we'll add the similar code there to configure the executor on the loop in use, but it seems it needs removing from, or fixing in, asgiref too. (I can't see an …
=> Removed support for ASGI_THREADS environment variable.

docs/extensions.rst
This gives an ASGI mechanism for the application to indicate to the
server what early hints to send.
See https://developers.cloudflare.com/cache/about/early-hints/, https://httpwg.org/specs/rfc8297.html, and https://www.rfc-editor.org/rfc/rfc8288.html.
I hope to implement this in Hypercorn and replace my server push usage.
=> Early hints extension

asgiref/typing.py, docs/extensions.rst, specs/www.rst
- Closes #141
Currently, there are two implementations of HTTP Trailer:
- https://github.com/encode/uvicorn/pull/1599/ (Uvicorn)
- https://github.com/nonebot/nonecorn/blob/nonecorn_dev/src/hypercorn/protocol/http_stream.py#L232 (Nonecorn - Hypercorn fork) - Commit that introduced it: https://github.com/nonebot/nonecorn/commit/222757f8da25fc5b716b790b93c23710942790b4
What this PR proposes doesn't match any of those two implementations. I've tried to simplify a bit...
The uvicorn one introduces a new key on the `http.response.start` called `trailers`, to show the intention from the application to the server that trailing headers will be sent. I think this is not needed. The server can understand the intention if the header `Trailer:` is provided on the `headers` from the …
=> Add HTTP Trailers extension

.pre-commit-config.yaml, asgiref/timeout.py, tests/test_server.py
@carltongibson The flake8 repo at gitlab got deleted, see [1] below for background.
As well as updating the repo link I updated the versions and fixed the errors those new versions were raising. 
[1] https://www.youtube.com/watch?v=1FIgj9Q5e6A&t=211s
=> Updated pre-commit versions

asgiref/compatibility.py, asgiref/sync.py, tests/test_sync.py
Refs: https://github.com/python/cpython/pull/99247
This would be needed for Django 4.2, which would support PY312 on release of that.
Adds `markcoroutinefunction()` and `iscoroutinefunction` shims, and makes use of those internally.
=> Added coroutine detection shims for Python 3.12

CHANGELOG.txt, asgiref/timeout.py
> The `get_running_loop()` function is preferred to `get_event_loop()` in coroutines and callbacks.
=> Updated timeout helper to use get_running_loop().

asgiref/typing.py, docs/extensions.rst
- Closes https://github.com/django/asgiref/issues/135
=> Add Debug extension

asgiref/sync.py, tests/test_sync_contextvars.py
Contextvars are unconditionally available since dropping Python 3.6 support in 02fecb6046bb5ec0dbbad00ffcd2043e893fcea5.
=> Simplified contextvars usage.

.pre-commit-config.yaml
Update isort to 5.11.5 due to https://github.com/PyCQA/isort/issues/2083
isort 5.12.0 is out too, but It appears to have already dropped support for python 3.7.
=> Update isort version in pre-commit

asgiref/typing.py, setup.cfg, specs/lifespan.rst, specs/www.rst
=> Add extensions["lifespan.state"]

specs/lifespan.rst, specs/www.rst
Addressing https://github.com/django/asgiref/pull/354#discussion_r1125446663 and https://github.com/django/asgiref/pull/354#discussion_r1125446411
=> Clarify ambigious section of lifespan["state"] spec

specs/lifespan.rst
✏ Fix micro-typo (nano-typo) in Lifespan spec: `state`
Just an extra backtick.
BTW, awesome job on the new `state` addition @adriangb :clap: :cake:
=> ✏ Fix micro-typo (nano-typo) in Lifespan spec: `state`

docs/implementations.rst
Update the docs section on applications frameworks to add [starlite](https://starliteproject.dev/)
=> add starlite to application frameworks

specs/lifespan.rst
Hi there,
This is a fix for the "Lifespan state" spec docs: https://asgi.readthedocs.io/en/latest/specs/lifespan.html#lifespan-state
The prose mentions `lifespan["state"]` but the example code shows `scope["state"]`. My understanding is that the latter is the correct reference.
cc @Kludex
=> Fix typo in lifespan state spec

asgiref/current_thread_executor.py, asgiref/sync.py
This idea came from ongoing work in https://github.com/django/django/pull/16636 to try and hide sensitive variables in an `async` wrapper for a synchronous function in the `auth` contrib app in Django.
Basically, Django supports skipping frames that have a truthy `__traceback_hide__` value in the frame's locals:
https://github.com/django/django/blob/85b52d22fd2841c34e95b3a80d6f2b668ce2f160/django/views/debug.py#L523-L527
We could take advantage of this pre-existing logic in Django and hide the internals of the `asgiref.sync` machinery.
Adopting this idea has 2 advantages:
1. Users don't need to see frames they don't care about, this leans more in to the "just call `async_to_sync`/`sync_to_async` functions and don't worry about the rough edges" concept discussed in the README
2. Hide …
=> Use `__traceback_hide__` to skip frames in tracebacks

asgiref/sync.py
This is a very simple patch. I noticed it in stack traces when I was working on https://github.com/django/django/pull/16636, and thought it was odd.
I took a closer look today and confirmed my hypothesis: this does nothing.
The definition for `asyncio.wait_for` when `timeout=None` just `await`s the future and returns the value:
https://github.com/python/cpython/blob/3.7/Lib/asyncio/tasks.py#L413-L414
This logic was added in Python 3.4 (predating even `async`/`await` syntax): https://github.com/python/cpython/commit/48c66c3dd82e0f345350f99d0c8713cc1e686939
(the logic was eventually modernized in https://github.com/python/cpython/commit/5f841b553814969220b096a2b4f959b7f6fcbaf6#diff-429f4ed1e0f89ea2c92e2a8e8548ea8ae1a3d528979554fbfa4c38329e951529R333)
The original provenence for this …
=> Remove extra call to `asyncio.wait_for`

docs/implementations.rst
[Starlite has been renamed to Litestar](https://litestar.dev/about/organization.html#litestar-and-starlite)
=> Rename Starlite to Litestar

asgiref/sync.py
This fixes a garbage-collection issue explained in: https://stackoverflow.com/q/76118191/326792
Current implementation of `sync_to_async` blocks python from garbage-collecting failed tasks with reference-counting. The explicit assignment of local variable `source_task` to `None` fixes this!
=> Better garbage-collection on exceptions in sync_to_async

asgiref/current_thread_executor.py, asgiref/sync.py
* Make sure `sync_to_async`/`async_to_sync` keeps the original function typing signature
* Define iscoroutinefunction/markcoroutinefunction at import time instead of an if/else in runtime.
The current implementation:
```python
In [7]: timeit.timeit(lambda: iscoroutinefunction(some_sync_func), number=10000)
Out[7]: 0.012024379917420447
```
Versus this PR
```python
In [11]: timeit.timeit(lambda: iscoroutinefunction(some_sync_func), number=10000)
Out[11]: 0.004663120023906231
```
This is a performance improvement of almost 300%.
=> Improve sync.py typing and utilities performance

CHANGELOG.txt
As per https://github.com/django/asgiref/issues/399#issuecomment-1589687227
=> Adjusted changelog for 3.7.0 to reflect that `Local` isn't `contextvars` yet

specs/www.rst
This was a point of confusion here:
- https://github.com/encode/httpx/issues/2810
=> Clarify that raw_path does not include the query string

asgiref/local.py, asgiref/sync.py, asgiref/testing.py, tests/test_local.py, tests/test_sync.py
Change the order of fallbacks used by SyncToAsync to find the appropriate executor for sync code, so it prefers to use AsyncToSync.loop_thread_executors rather than thread_sensitive_context. Add test case to demonstrate problem.
Resolves django/asgiref#348
=> Allow nesting sync_to_async via asyncio.wait_for

specs/www.rst
Provide some additional context regarding Cookie and Set-Cookie, in regards to how it behaves differently on HTTP/2.
Also note clearly that '; ' is the delimiter for Cookie, not comma.
Fixes #420
=> Rewrite section of HTTP spec re Cookie headers

docs/implementations.rst
. Added Esmerald to implementations.
. Ordered the list alphabetically
=> Add Esmerald to implementations

tests/test_sync.py
I noticed asyncio.shield doesn't work as expected when using sync middleware, I've wrote two tests, one which passes for async middleware and one which fails for sync middleware.
=> Test asyncio.shield with sync and async middlware

asgiref/sync.py, tests/test_sync.py
=> Fix task cancellation propagation to subtasks when using sync middleware

asgiref/sync.py, tests/test_sync.py
Think I got the tests in #439 fixed.
=> Move variable initialization in AsyncToSync from __init__ to __call__

asgiref/sync.py
=> Raise exception if exec_coro is done.

README.rst
The `build` module doesn't create the `build` folder in the local directory. It's probably also worth cleaning up the .egg-info in the last step.
=> Updated release steps in README.

.readthedocs.yaml, docs/conf.py, docs/requirements.txt
On [2023](https://blog.readthedocs.com/defaulting-latest-build-tools/), RTD made changes to the tools that are automatically installed. I'm pretty sure (though that might a false memory) that the Asgi doc used to use the rtd theme. Fact is that it now uses the default theme which looks [_so retro it belongs in a museum_](https://fosstodon.org/@carlton/112140615717929142).
This PR resets the theme to RTD.
What this PR exactly does:
- Add a docs/requirements.txt file with docs dependencies
- Change the value for the theme
What this PR doesn't do but could (you tell me):
- Pin dependencies in docs/requirements.txt (I don't see dependabot or renovate being used in the repo so I'm wary of adding pinned deps, as they'll likely get old quick)
- Use a more modern theme such as Pradyun's excellent …
=> Reset doc theme to ReadTheDocs' default theme

asgiref/typing.py, specs/www.rst
This is a proposal to fix the discussion in #459
Clients can send this reason field when disconnecting. This is allowed as per RFC 6455 and supported in browsers JS API, but previously not supported in ASGI.
---
I took the liberty to bump the spec version, but I can remove it if you prefer 🙂
=> Spec: Added `reason` to WebSocket Disconnect

specs/www.rst
`IOError` is an alias to `OSError` on Python 3.
=> Replace `IOError` by `OSError`

specs/www.rst
I noticed a tiny gap in the ASGI HTTP spec for `scope["asgi"]["spec_version"]` - all valid versions are explicitly enumerated, but that list hasn't been updated to include newer versions of the ASGI HTTP spec.
This change rewords the spec so the list of versions doesn't need to be updated every time there's a new version of the ASGI HTTP spec. I'd also be happy to just add the newer versions to this list instead, but then someone would also need to remember to update it in the future too.
I tested this by rebuilding the docs locally and viewing the changes in my browser:
=> Update HTTP spec: correct `scope.asgi.spec_version`

asgiref/sync.py, tests/test_sync.py
Fixes #470.
Destructuring `*args` and `**kwargs` passed in by the callee has the chance that the same kwargs names may be used as by `main_wrap`. If that happens, the interpreter will raise a error like: `TypeError: AsyncToSync.main_wrap() got multiple values for argument 'context'`.
`ParamSpec` requires the `*args` and `**kwargs` syntax to be used, but it is wrong execution wise.
So we work around the issue by pre-creating the awaitable outside `main_wrap`, which removes the need to pass `*args` and `**kwargs`.
Another alternative instead of creating the awaitable could be to use `functools.partial`, though that does add some performance overhead: https://github.com/django/asgiref/issues/470#issuecomment-2377074109.
=> Fix #470: Prevent error `AsyncToSync.main_wrap() got multiple values for argument '<kwarg>'`

asgiref/sync.py
current_executor is set unconditionally in the same block above.
https://github.com/django/asgiref/blob/a1f8be5ad33096a0885a60cbad1e6befba84119a/asgiref/sync.py#L199
Just a small cleanup, whilst reviewing sync.py.
=> Remove unneeded check in AsyncToSync.

asgiref/local.py, tests/test_local.py
Reproduce issue #473 in asgiref's test suite
Fixes #473
=> Fix Local behaviour with asyncio Task. 

specs/www.rst
Discussed in #468, `raw_path` of WebSocket is updated for clarification.
=> Clarify `raw_path` of WebSocket also excludes query string

setup.cfg
See issue: python/mypy#17960
Fixed in master: python/mypy#17355 after last release v1.3.0.
Checks have been failing since mypy 1.12 release: 
```
asgiref/sync.py:291: error: Too few arguments for "__call__" of "AsyncToSync"  [call-arg]
asgiref/sync.py:466: error: Too few arguments for "__call__" of "SyncToAsync"  [call-arg]
```
=> Pin mypy for regression in v1.12.

setup.cfg
Regression in mypy v1.12 was resolved in v1.14. Use that as a minimum pin (rather than clearing it) to force/suggest/trigger an update for existing environments.
Follow up to #484.
=> Update mypy pin.

asgiref/sync.py
* `asyncio.get_running_loop().is_running()` is redundant
* checking `is_running` before `call_soon_threadsafe` is redundant because `call_soon_threadsafe` checks it, and the loop could have stopped between the check and the call
=> Avoid using event_loop.is_running()

CHANGELOG.txt
#505 made send_input &co return the result if the application is already completed. Note this in changelog, as it may require test updates.
Closes #518.
=> Adjust changelog for ApplicationCommunicator updates.

asgiref/local.py, tests/test_local.py
https://github.com/django/asgiref/commit/85d2445021ff8e588fb2883a865d768b60bd0902#r161477713 changed the `ContextVar` to be a dict of `ContextVars`
While that does work in preventing the contexts to leak, removing a value with `del local.value` completely removes the `ContextVar`, literally unsetting it from all other contexts.
As we discussed [here](https://github.com/django/asgiref/issues/475#issuecomment-3043620092), using `.copy()` is simpler and should have no downsides compared to the current solution, especially since it is a shallow copy only
This PR reverts the mentioned change and instead uses a `.copy()` for both `__setattr__` and `__delattr__`. The added tests there still pass for this solution, and I also added a new test that would have caught this issue.
Fixes #522
Fixes …
=> fix: prevent deletion of Local values from messing with other ctxs

CHANGELOG.txt, asgiref/sync.py, tests/test_sync.py
I have a problem with async database connections for `Django` `TestCase`.
The psycopg3 connection is not thread-safe. As a result, I need to create a new connection per thread. This is a problem for the `TestCase` coz it uses a transaction for each test case.
```python
class TestCase(TransactionTestCase):
async def _apost_teardown(self):
for conn in async_connections.all(initialized_only=True):
await conn.close()
def _setup_and_call(self, result, debug=False):
if iscoroutinefunction(testMethod):
############### convert test 
setattr(self, self._testMethodName, async_to_sync(testMethod))
if debug:
super().debug()
else:
super().__call__(result)
self._post_teardown()
############### convert teardown 
async_to_sync(self._apost_teardown)()       
```
I can do something like that coz each …
=> added AsyncSingleThreadContext
