asgiref/base_layer.py, asgiref/tests/test_base_layer.py
added validation method that accepts list of channel names.
=> validation method for multiple  channel names

asgiref/wsgi.py, tests/test_wsgi.py
=> bugfix always send http.response.start

tests/test_local.py
As discussed at DjangoCon Europe
=> Add tests showing threads and method locals side-by-side

asgiref/wsgi.py
Set REMOTE_ADDR in wsgi environ.
=> Add client info into wsgi environ

specs/lifespan.rst
The actual protocol remains unchanged.
=> Fixed #97: Reworked Lifespan example to ASGI 3

specs/lifespan.rst
Lifespan's document was broken.
=> Fix broken document `lifespan`

asgiref/wsgi.py, tests/test_wsgi.py
=> Handle request body split across messages in wsgi

docs/extensions.rst
See commit messages
@jlaine look good to you?
=> Clarify aspects of the server push extension

asgiref/sync.py, tests/test_sync.py
=> Add support for naive introspection of wrapped sync_to_async functions

specs/www.rst
=> Add notes about Transfer-Encoding: chunked

asgiref/local.py
The _context_refs array of weak references was only freed
when the whole Local object was deleted: even when the
referenced objects weren't there anymore, the array of
empty refs was still there.
This is a problem in django where Local() objects are kept
at the global scope in multiple places and never cleared.
=> Fix memory leak in Local

specs/asgi.rst
This PR is a minor wording update of the spec.
It mainly deals with rewording the parts that used to refer to the 2-callable design in ASGI 2.0.
There's a small text update to show that although `asyncio` is the canonical implementation, it is not required by the spec, what is required is `async` / `await` coroutine support.
It clarifies a bit the types and usage of the arguments passed to an ASGI app.
There's also a small clarification to make explicit the *connection scope* as a technical term used by the spec to include the lifetime of a connection and the `scope` parameter passed to the app with *connection scope* information.
There are also some other minor wording updates mostly for consistency with the rest of the spec and to try and reduce any possible ambiguity.
---
This is part …
=> 📝 Minor wording update: ASGI spec

specs/www.rst
This PR is a minor wording update for the HTTP and WebSocket sub-specs.
It mainly deals with rewording the parts that used to refer to the 2-callable design in ASGI 2.0.
It also includes some minor rewordings for consistency with other parts of the spec.
And some minor updates to make the types and directions of events a bit more explicit and reduce any possible ambiguity.
---
This is part of several PRs I'm making while reading and re-reading the spec several times.
The main purpose is to try and update the parts that contained text based on the 2-callable version (2.0) and to clarify a bit more the parameters passed to an ASGI app and types and direction of events.
=> 📝 Minor wording update: HTTP - WebSocket sub-specs

asgiref/sync.py
Fix #170 again. This has been run against the Django master testsuite.
Not entirely sure if this performs. Do we have a benchmark suite for this (in Django)?
=> Rewrite how context is propagated in AsyncToSync

asgiref/wsgi.py, tests/test_wsgi.py
fix #182 
The latin1 encoding is required in WSGI, and the utf8 encoding in ASGI.
=> fix encoding error

specs/www.rst
The rst seems a little bit off for the last 2 titles in `www.rst`
=> Title level inconsistent

docs/extensions.rst
=> Add ZeroCopy extension

asgiref/server.py, tests/test_server.py
whereas the update does not released, please fix #209 with that workaround...
=> Update StatelessServer to use ASGI v3 application. 

asgiref/current_thread_executor.py
https://github.com/django/asgiref/blob/7dba5ff61313dfd1535de200590b9155abde20f0/asgiref/current_thread_executor.py#L56-L68
`CurrentThreadExecutor.run_until_future()` keeps busy checking two things:
1. Do I have something to do?
2. Is the future I'm tracking done?
with a short sleep in between iterations.
I noticed this when I was wondering why some threads I had running, which should be doing basically nothing, were using noticeable, though relatively low, CPU. (~5%) This was in three long-lived django helper processes running async event loops in an app I'm working on where that process count will scale as 2+n_users, so I had concerns about this CPU use as I prepared to add more users.
Because we're checking two things, we can't block on checking one thing, necessitating the sleep to …
=> Reduce CPU usage in CurrentThreadExecutor.run_until_future()

CHANGELOG.txt, asgiref/sync.py, tests/test_sync.py
=> Add type checks for functions passed to async_to_sync/sync_to_async

CHANGELOG.txt
=> Add missed changelog notes for 3.3.2

tests/test_wsgi.py
fixes https://github.com/django/asgiref/issues/265
=> Improved coverage on same header keys

README.rst
Fix misspelling of "crucially" on the README.
=> ✏️ Fix typo on the README

docs/implementations.rst
This info might be useful for adopters.
=> Improve docs - Starlette supports WebSockets

specs/lifespan.rst
Fix Version History and Copyright level under Lifespan Protocol chapter.
=> Fix a Typographical Error.

specs/www.rst
=> Improve wording on 'WSGI Compatibility' section

specs/www.rst
=> Reword contract for http.disconnect

.github/workflows/tests.yml, setup.cfg, tox.ini
Hi there,
This PR aims to add Python 3.11 support to the tests.
<details>
<summary>Test Log ( Python 3.11 ):</summary>
```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
PS C:\Users\Asus\Desktop\asgiref> pipenv install .
Creating a virtualenv for this project...
Pipfile: C:\Users\Asus\Desktop\asgiref\Pipfile
Using C:/Users/Asus/AppData/Local/Programs/Python/Python311/python.exe (3.11.1) to create virtualenv...
[  ==] Creating virtual environment...created virtual environment CPython3.11.1.final.0-64 in 5285ms
creator Venv(dest=C:\Users\Asus\.virtualenvs\asgiref-jlv6g4Kh, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Windows)
seeder …
```
=> Added  Python 3.11 support

asgiref/sync.py
=> refactor: type sync_to_async/async_to_async as returning callables instead of the SyncToAsync/AsyncToSync

asgiref/typing.py, docs/extensions.rst
=> Add `pathsend` extension

asgiref/wsgi.py
This fixes #410. Please see the issue for a description of the change.
=> Handle `"client": None` in WsgiToAsgi adapter

docs/implementations.rst
[Connexion](https://github.com/spec-first/connexion) has joined the ASGI ecosystem with its 3.0.0 release in which it adopted the ASGI interface.
=> Add Connexion to implementations.rst

MANIFEST.in
=> Add tox.ini to MANIFEST.in

docs/implementations.rst
Added MicroPie to the Implementations page.
=> Add MicroPie framework to `implementations.rst`

tests/test_garbage_collection.py
=> Skip garbage collection test on PyPy
